os: osx
language: node_js
node_js:
  - node
before_install:
  - openssl aes-256-cbc -k "$pass" -in resources/random.enc -out key.json -d
script:
  - yarn test:cov
after_success:
  - if [[ "${TRAVIS_EVENT_TYPE}" = "cron" ]]; then ./upgrade.sh; fi
deploy:
  skip_cleanup: true
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    tags: true
env:
  global:
    secure: 4g/rlOkzJ21sSrw1cuHLzA/NLmZGpKfvpqP537CTXJkUaHKxpH8b3hHLmPkAFtkYoBu6NklPOa0OxuzGPLe7w0iCiwNPCPr1iEAO4j+oZJfXH9n+3vwiQPvHS2e8EChEG8QSzzfLzsya6K25JTG/PGowMr4jAiOXBM9vPj2O8ixaAnQukUZOWD5ohPeOP0PDhflGeWfRAlsBVufWASeuz7vL50pVXHY3j+VH/H2Ndhx7NHRrY4QXR1DldxUKVOVpDM9DWrjeyLadXbOAQQpyWDDkOAMbuj8lMkCGSLMXEjIO9zS2eWlTnqN8fPiDteWjlxSe42Pt7Vwp9+DO0b2fxsJqngdsbjt/TTiAaaY/mLt8Gf6XgZV1dZr4HXNuUdmS1RgFoI4fhrEYETG9mZQ20nA74diBLQISNTKPpREmJANftq6ziuNFpwxp4FulcJukCfgKP1zvpVTasrBDPM4GiiUSOeYgM18d/VFFl0MqzCsiUBt31N+LKJS0y09QyOc/FADjhqkVNJLlonP55umGYphoFZNw4USP9UlmAEP8o0IO4qgIrnu4H/X5nfpBy3hMBgwJejAk/bRtWwp2rICy7mZ6lfaPGkFN8zBowEdLZdn3cpCZtZ1DQoTmDAeuEdOPnbxvOgd7Ha6+c+h02tXmqkRmkuxATLnNmjhiD5PCDt8=
