language: node_js
sudo: false
node_js:
- node
before_install:
- openssl aes-256-cbc -K $encrypted_f0cb5834ebc7_key -iv $encrypted_f0cb5834ebc7_iv
  -in ./resources/random.enc -out ./key.pem -d
script:
- yarn test:cov
deploy:
  skip_cleanup: true
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    tags: true
env:
  matrix:
  - secure: zCoLYvAbZq3lzgtpMNFxmbD/L0kUmwTCVfAy73xNvhsV2UoiSZcD6TvNztGQ3LEm6MjF4WSdEloRAi8v3xebN3G/mO79ACDprWdxBmr9fi2A/vmx3vJpQogQMww9ZzQZ3PHTlBwZMFMW9qGr+zOOmSVlH41cxnaY1q2rq7fcCgBlxzUz6hTCxmxeXObbyUK6xjyBaYY7xw4GLK71xqfdRT5gZD4SM4T8KPQVthzizYrFFqFMvhxJHQdnhirSdpHBCp4XOdfBN+jmC3M5ab/jUFhjEStoAw59RJwaTCNI91WbvSuPFKF0N3PbH/ecWDxQ0ZghqeNH6KXtFcMgchEkAZAT/gZm84UFxZk8Gw/MJfDvEwHjqpMQwpRl6vhl9OGz0FYRyZyZCZ9ZsrD1QDkxwmCkNXOULIaWje2oNaeObVR4MjBELvNxkiOem12AR3STLv0tVnI5qffebTHJF0k6Z/inIqortdBhUXFQTl3OayrBgCFQjCYg1T7CCPgISxBY3194PV63E1x28EC1u48AY6imWrERN+/IPIY6j3A7+8/DtsFCJa+SGyhXeOsD+ldHeLBbqPleYWE9unl4zdRSQvAo9MyrtlhnWKJTrFUc4TGjnIShEW5aETPFAwm724wAkRPDU3VkjQ9VkeZswHxGICkR1JsH4mKZqTqM36AVhQI=
  - secure: bW/oMvcHicPuS2egMz3dLCT9fPwTrcAqc9ENDisRtOkr4qmITc+SWj5feLv06O+M7O4vFT1UrXP4eXHXLW9xDZndePxpC/I/KWGlgeKlp/2bMZ5yXlQfgSAIKqW7A4nYXca5gc8JHM1C+RYoezRyaGt/72HxXxAteOwdLvy2jeAnwxaOd2iX01ZvQbG5FUUoSkZvF/Dynu4KgxiaUVIIa0yQU8DqEiYBwMND2GN+R1qWYWfwlqRJ9jwRz35u/mFTMuRQLkhCaD8909fKOY4xdUHZN3hjkY0DMr0W2xrgf8bxIX2QdsKuiUGgDlTL65YuB8v5G1fZtkKXDVPmnBgjXUb6RZLA/puWDra82ivLPgjK1g/dm3hYL0f3kEzyCXTppLulf48wGXdAHiNt07O5XYvTm6rzLewssGmWonGSK0RMovphBVqfMVvyarGzZS98CAr4XVQmmF5M4wO2w72Ap5XgcDbhh+vtG/I4EK4STjtI02pHx+QDzhdOVQ5hW5CRdBEX+M6TVJi3GvQ8WG5buyMARCvomM9Vd8ZmxvJeiJON7vSezf/crVlkVAD9R/sqjnLA2t3nInEbhdbF/bAwGUoT53jUjE4giP2EBHIdGVet3SIf++/0KVoXvaF/EZj2PpZauNW6zvRINRWOtGKnpv2SUy7w7MHpSmLZyYtAflo=
