os: osx
language: node_js
node_js:
  - node
before_install:
  - openssl aes-256-cbc -k "$pass" -in resources/random.enc -out key.p12 -d
script:
  - yarn test:cov
after_success:
  - if [[ "${TRAVIS_EVENT_TYPE}" = "cron" ]]; then ./upgrade.sh; fi
deploy:
  skip_cleanup: true
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    tags: true
env:
  global:
    secure: nqzPpSYbY7VWvUPmbQBeSlCHXVKNLgJHko3CS3BXq+Wiv81lmm44tK59l8ORjy4JqAtRNrKaBiLj+Eikki5NMrQ+1kWf34wxNSJBCUIkZmcSLY92hTLeFwUW79q48ZEFkX6pYDKkrkqdtPfRYLI9PmyhKaFlbJtjTkaIFEj6rKLoUSDdb2Z+b5r4J3F0ENYBZWhABMwtnOaae2bk6LJ8nJdceHmQwRXhXuNl4EEC5QsN9TjCXrTeIn05paazYCjXftzXEBFOnj5T9DClcnLnZeQV62Sksabvu/aRIbCKpd+UmVEs2o88hP53nlwY4Y66YZffbV+Ef16dimMIuyl/0J63SHaPzX9Z+oOhcohfxuESnsrogbBxRBdL5Lq+SyVkfaWJ1tKUhb1zeXrGVuOxgso3tk+CvJa04G+E50a6RoCC3d2hs0Y3f2Uh1WsjBQYAf7Rkdls2OJMqZg16ObL4w4k60e3VmytnxYX5FA/ZXTQpLzq+9DJNckWvl2ABBWxzpG7q7CUHHGqQDx6vpF9wj7OLatk8GovZN4xH3WydX0GSrIFcyyvq++KWl5C0rxG3VYIPLkOE9ABNw+SmoatdzKIDkYchG+0Pivui4cmnF56+WuKF1RHzliUtf9hSwEQeBhiY8Rwrr3ZxOwUOcFF/oLsacE1vlHYnMAOyC9gqEyw=
