os: osx
language: node_js
node_js:
  - node
before_install:
  - openssl aes-256-cbc -K $encrypted_f0cb5834ebc7_key -iv $encrypted_f0cb5834ebc7_iv -in ./resources/random.enc -out ./key.pem -d
script:
  - yarn test:cov
after_success:
  - if [[ "${TRAVIS_EVENT_TYPE}" = "cron" ]]; then ./upgrade.sh; fi
deploy:
  skip_cleanup: true
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    tags: true
env:
  secure: xTVGJgcYp2PwxoQcCecr6RKuI2xrCwh2SSUY0Osg1cM4Co9tgMYmjB/E3LgTBHbJIPqeboLJZg2qJpqm8skdOFpX6zOVS8LRQuB9hNg/TsOPQgL6t9JeiAT4KczqfCwCovc3toIjBKBeU6YQ5hNL4D5h2HnmfF9Y8Okxv/5jblnGnnZ0j8oq2tRvAAcz9xGvw02ZWnBQyC2jsbKEnYks8FHFfqPvswZT69lXbD+hN9Fv0pC1o68FBTEOrmJjuDgp7bGhQV8RN9vy1NBC5nOkLCvg4pGFx9YCgg2jmoUI91/t02cpsD5mDII/fXajx/moW1er/HURYq0IG61KXA2Uypn3Ul/a8EaMzVrMfUGXBi1Cr2SjSaYLy94A0MAPh8FKVlXtKd+lF6r3z2yBOl6cq5mSTJHQJuI8/WLd/TvgNudn47YFiRqw4/nb7Inrxni2hP33fxfdXgmLD/CWVUi7YogiqDhHt8RzIsawtzJAynH85LdgipcZYFBkSgD+qzxnvNBvMQm5w9B8tRXZ/vQdbebQblY0TdkORd/F/i+hZY7VCiXSb03083ogNQ33Nj+dIHET6qK34VnIsMGo1NZqiL5Ls8udbrO64vfv7xRizBuEybS2Q0WS8Bejzt4KO4hJDR0FDwC5dogXJuaJTR63sEGbHluCVyaTiG0wFHi5hYk=
