language: node_js
sudo: false
node_js:
- node
before_install:
- openssl aes-256-cbc -K $encrypted_f0cb5834ebc7_key -iv $encrypted_f0cb5834ebc7_iv -in ./resources/random.enc -out ./key.pem -d
script:
- yarn test:cov
deploy:
  skip_cleanup: true
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    tags: true
env:
  matrix:
  - secure: v9NTdX6Xe04h9HdaB5xCz3CEPA9i3AfWVt45MiDljfWtFfk42kkDmZoP/mMRvXK6zrvmUcHq8p/236DLN5BkIOkLEAKWuJI0ZIoq4e0lyWH4gWlexwpjTqkFzehBl5f35Pep5bsF4sxRlryNuyK7BF1eWtfB6xbn9Lz7Pvo3XzqKAjgd4guIKkXub1B/yk3URgtPbA9aGtQgt8caciV3dBcwPeFyrOep4kOVN9Mp23SkuH70cefv91gmkWJQXVF4MY8TlQe3lrzI4oUHCdj9Ka+igzZFKqAS9/sn9yVawmp6kfxrI5SqpGZ32vlciL1YZkW9puwgjwJhS0xLfL2y6iSw1HFrAjrzN7lUE6ikFbdrlwYTiJxz4jl6bHIYNRJT2PAyjgsz1C5zmTwayDw13P18SUTqhSuNVG7R+tu4qIwi5KyqutDdtHYD1GN7OHqB5RiGrKr3S8AndhLfEk4Mv+vsLXb6JJhhR/B3UQJALpTsT52ffvHf8TKU1Zo6DmHnuGhLqQoh2gidZaEuYWrRqF1G2bjUubbbc/x9gyF9BoyaLNleyXC43l18Z556reyCnUfA5ksgSqsty7GKZt4iG0v1LZpXbu5oNZUBbaLyUTWrqMGbAh64D9P2urHRrZ5rcLyem5VkdjpKQyGmP3ChT+3C/AEFbG8sB/MNuq5pfEM=
  - secure: z+PCMBfz2lk6BnTJC2AugvCdZKSIQhKAUq6ahyjwpXl7GSDjgh+WuW2/7tG5CEtjCb4qeJDlQb01Oq7aMyT11EhMdxpOu+D05Q4L2ORvU5R/d66pjyUiliT6jMBiTrl/jQ7b/1OEPLslazLakgJe+vfv27pGXrrVNwMyJEQIw0d6cpiF7kCh2CatF8rdf+kof8+hy52BGNvLcM+nyUQHGxQ5qSKqZvkzc5J0YxJE8EpHl/jUdQTBnWSHzq+nBRs6J0Zl1buZdIT1AWvqcAOhf0bbJEJmsdfRdlwxpDBmf0p0Ef5TU/2iYFhuNb4zqJTse5nX9ieBFX1VenE8xqZupvrbTlqusKoP1btJ2T8hw6OoxkVJLvu6sacBlIl9/rGf9y4a1ahaF232/bjyiec7RsdL9+UvB21EHHR96bIWSZYYjn7r76DHiqEw+CJaAkuyREJmJLDpOhpZZLLYyfv/VL2ZqOHzFP0vRDwMV+Cz6m4tDT7C/W5oN9yA8TEE959bd2DDXFfCYygiEKqivTWIbQPCxoRf088ct98GJl5Fo8lrOykv8Uqf7OuDUF6zTiwmTHBAMDBtEOyObf+TdkbG31US5nf3tuAmIwKpmZOnVHLq+4PZOLXlJSmgRHTwKlWkSOe0ismTsD2mVrAKb2PvOSTzMQcSebj0bwFP76PIoEs=
