language: node_js
sudo: false
node_js:
- node
before_install:
- openssl aes-256-cbc -K $encrypted_f0cb5834ebc7_key -iv $encrypted_f0cb5834ebc7_iv -in ./resources/random.enc -out ./key.pem -d
script:
- yarn test:cov
deploy:
  skip_cleanup: true
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    tags: true
env:
  secure: eytAmptYxGe6SQ1PHX1EPAIEoAgF6+WIyTKbxUCkQssVvmZpTZw6+UPRGQfftWUANv88bC2wahg1Q9riQqNXrwm9z1dFIjjSkRbej6T/xDuzOpw9C/xq/BTlHFQqytYPwAwo+JBbk40dK9iohtHkVCbgVpGi/XMdvsfzJCb8+A0Yhh187USoyI/HZ2YfcSwxwF6p0E3Hdx/QdB7QSW/pmYn8CwWwBa6msqAD8PMwYh97s1pRVCAmYJVwWQeVCGTmkIdkRYt0u+tzRODRVFMmIFama4PhR8/6vvsG0B6FRnROnJTuX5x3kvbHUyeX/DJZnvbbGPlEkMzrU3SKLWPjGUXV2xs1CVTk/eY4XNx80xPYrQr9lRijYBFvnnUAFnQIGTDqc8Dd09jIQWia9Z8ADAq285dWmu0iQBKoaDq/vABdl2FMe7TMCVuFy8NiR3SIT5rsLyiMzYwXpQsya12FcOKbvkjovWj8PunBZPn1UoThpwsD+MlX/DqMqJg+7YOp+kL++DKhxVOLZ+Qe1lmmfgSfa3M7PHe+4N74o6iTugRNpr2NpwHAo8Sz/YLWLb0egCe/k448I/aGjiDYYGLT8JeqHaPYoAw/Yuxb4EZ2kp2dgH+vLRowW71rC5sMtBnkbdg3fMfiER71lHdLI8BJ78lwe22ogooClWq3Sln03EI=
